### ISSUE TITLE
Display a warning when user is not authenticated

### ISSUE THREAD

**Issue by jyntran** [jyntran/nhaccuatui-scrobbler#13]
When a user is not authenticated, display the message in a dark yellow colour under the track metadata: `Please log in to scrobble`

**Comment by kejriwalayushi28** [comment]
@jyntran I would like to pick this issue .

**Comment by jyntran** [comment]
@kejriwalayushi28 Sure, give it a try. Thanks.

**Comment by imthinhvu** [comment]
@kejriwalayushi28 - since I didn't see any activity on this, I ended up making a PR. Please feel free review and suggest enhancements, or make them after the fact.
