### ISSUE TITLE
Add Vietnamese localization of the Privacy Policy

### ISSUE THREAD

**Issue by jyntran** [jyntran/nhaccuatui-scrobbler#19]
The [Privacy Policy](https://github.com/jyntran/nhaccuatui-scrobbler/blob/master/privacy.md) is only available in English. It would be greatly beneficial to have a Vietnamese version as well.

**Comment by CharaeKeow** [comment]
Is Google Translate the Privacy Policy reliable? If yes, then I would like to help.

**Comment by jyntran** [comment]
@CharaeKeow Sorry, no Google Translate for this.

**Comment by CharaeKeow** [comment]
@jyntran Okay.

**Comment by imthinhvu** [comment]
@jyntran - I made an attempt at this, please let me know if it is adequate or if we should make some edits.
